# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build"
  lane :build do
    cocoapods(repo_update: true)
    simctl(block: lambda { |other_action, device|
      other_action.build_ios_app(workspace: "#{Dir.pwd}/ROCM.xcworkspace",
        scheme: "ROCM",
        destination: "platform=iOS Simulator,name=#{device.name}",
        skip_archive: true,
        skip_package_ipa: true)
    })
  end

  lane :test do
    simctl(block: lambda { |other_action, device|
      other_action.run_tests(workspace: "#{Dir.pwd}/ROCM.xcworkspace",
        scheme: 'ROCM',
        device: device.name)
    })
  end
end
